spring:
  application:
    name: softprogy-balancer

server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
zuul:
  sensitiveHeaders: Cookie,Set-Cookie